@startuml
'https://plantuml.com/activity-diagram-beta

start
:SplahActivity;
if (check token) then (true)
else (false)
 :LoginHost;
 split
   if (login with third party) then (yes)
   else(no)
    stop
   endif
 split again
     if (login with phone number) then (yes)
       else(no)
        stop
       endif
 split again
    if (login with password) then (yes)
           else(no)
            stop
           endif
 end split

endif

 :MainActivity;
    split
    :Video;
 split again
    :News;
 split again
    :User;
 if (Logout) then (yes)
    stop
     else
    endif
 end split


@enduml
