@startuml
'https://plantuml.com/use-case-diagram

User -> (Start)
(Start)  --> (Play welcome animation)
note right of (Play welcome animation) : this a Lottie Animation in loop.
(Play welcome animation) --> (check token)
note left of (check token) : Store in cache.
(check token)-->(Start home page)
(check token)-->(Start login page)
@enduml