@startuml
'https://plantuml.com/activity-diagram-beta
 :开始;
  fork
    repeat :需求文档;
      backward:<b>不通过;
    repeat while (需求评审)
     :原型设计;
     :UI设计;
  fork again
   :开发环境搭建;
   :安装IDE;
   :设备调试;
  end fork

  :创建工程;
  repeat :编写代码
  backward:<b>不通过;
  repeat while (<b>测试)
  :优化;
  :打包发布;
 :结束;
@enduml
