@startuml
'https://plantuml.com/sequence-diagram

autonumber
用户 -> 登录系统: 登录操作
登录系统 -> 缓存: 存放token

用户 <- 登录系统 : 认证成功返回token
用户 -> 登录系统: 下次访问头部携带token认证
登录系统 <- 缓存: 获取token
主页 <- 登录系统: 存在且校验成功则跳转到用户请求的其他模块
主页 -> 视频播放
主页 -> 新闻阅读
主页 -> 个人中心
用户 <- 个人中心: 点击退出按钮，重新登录
@enduml