@startuml
'https://plantuml.com/use-case-diagram

User -> (Splash)
Splash --> (LoginHost)
LoginHost -> (show animation and play in loop) #black
note top of (show animation and play in loop) : Two animation types: light mode and dark mode.
(LoginHost)  --> (BUTTON:Login With OTP)#green
note top of (BUTTON:Login With OTP) : Two receiving methods: SMS; Audio.

(LoginHost)  --> (BUTTON:Login With PassWord) #red
(LoginHost)  --> (BUTTON:Login Third Party)#blue
(BUTTON:Login With OTP)  --> (LoginMobileNumberFragment)#green;text:green : click button
(BUTTON:Login With PassWord)  --> (LoginPassWordFragment)#red;text:red : click button
(BUTTON:Login Third Party)  --> (WXEntryActivity)#blue;text:blue : click button
(LoginPassWordFragment)  -> (BUTTON:CREATE NEW ACCOUNT)#red;text:red
(BUTTON:CREATE NEW ACCOUNT)  -> (LoginSignUpFragment)#red;text:red : click button
(LoginMobileNumberFragment)  --> (BUTTON:Verify)#green
(LoginMobileNumberFragment)  --> (BUTTON:Send OTP)#green;text:green : click button
(LoginPassWordFragment)  --> (BUTTON:Log In)#red
(WXEntryActivity)  --> (CALLBACK)#blue
(BUTTON:Log In)  --> (Server Database)#red;text:red : click button
(BUTTON:Verify)  --> (Server Database)#green;text:green : click button
(CALLBACK)  --> (Server Database)#blue;text:blue : click button

Server -----> (Server Database)
(LoginSignUpFragment) --> (Server Database)#red
(Server Database)--> (MainActivy)
(BUTTON:Send OTP)--> (Server Database)
(Server Database)--> (Have OTP)
(Have OTP)--> (LoginMobileNumberFragment)

@enduml