@startuml
class com.he.fastandroid.ui.adapter.NewsAdapter {
# void convert(com.chad.library.adapter.base.viewholder.BaseViewHolder,com.he.fastandroid.entity.NewsList.NewsItem)
}
class com.he.fastandroid.entity.NewsList {
+ boolean remove(com.he.fastandroid.entity.NewsList.NewsItem)
+ boolean remove(java.lang.Object)
+ boolean contains(com.he.fastandroid.entity.NewsList.NewsItem)
+ boolean contains(java.lang.Object)
+ com.he.fastandroid.entity.NewsList.NewsItem removeAt(int)
+ com.he.fastandroid.entity.NewsList.NewsItem remove(int)
+ int indexOf(com.he.fastandroid.entity.NewsList.NewsItem)
+ int indexOf(java.lang.Object)
+ int lastIndexOf(com.he.fastandroid.entity.NewsList.NewsItem)
+ int lastIndexOf(java.lang.Object)
+ int getSize()
+ int size()
}
class com.he.fastandroid.entity.NewsList.NewsItem {
- java.lang.String alias
- java.lang.String boardid
- java.lang.String cid
- java.lang.Integer commentStatus
- java.lang.String daynum
- java.lang.String digest
- java.lang.String docid
- java.lang.Integer downTimes
- java.lang.String ename
- java.lang.String extraShowFields
- java.lang.Integer hasAD
- java.lang.Boolean hasCover
- java.lang.Integer hasHead
- java.lang.Boolean hasIcon
- java.lang.Integer hasImg
- java.lang.String imgsrc
- java.lang.String lmodify
- java.lang.String ltitle
- java.lang.String mtime
- java.lang.Integer order
- java.lang.String pixel
- java.lang.String postid
- java.lang.Integer priority
- java.lang.String ptime
- java.lang.Integer quality
- java.lang.Integer replyCount
- java.lang.Integer riskLevel
- java.lang.String source
- java.lang.String sourceId
- java.lang.String subtitle
- java.lang.String template
- java.lang.String title
- java.lang.String tname
- java.lang.String topic_background
- java.lang.String topicid
- java.lang.Integer upTimes
- java.lang.String url
- java.lang.String url_3w
- java.lang.Integer votecount
+ java.lang.String getAlias()
+ java.lang.String getBoardid()
+ java.lang.String getCid()
+ java.lang.Integer getCommentStatus()
+ java.lang.String getDaynum()
+ java.lang.String getDigest()
+ java.lang.String getDocid()
+ java.lang.Integer getDownTimes()
+ java.lang.String getEname()
+ java.lang.String getExtraShowFields()
+ java.lang.Integer getHasAD()
+ java.lang.Boolean getHasCover()
+ java.lang.Integer getHasHead()
+ java.lang.Boolean getHasIcon()
+ java.lang.Integer getHasImg()
+ java.lang.String getImgsrc()
+ java.lang.String getLmodify()
+ java.lang.String getLtitle()
+ java.lang.String getMtime()
+ java.lang.Integer getOrder()
+ java.lang.String getPixel()
+ java.lang.String getPostid()
+ java.lang.Integer getPriority()
+ java.lang.String getPtime()
+ java.lang.Integer getQuality()
+ java.lang.Integer getReplyCount()
+ java.lang.Integer getRiskLevel()
+ java.lang.String getSource()
+ java.lang.String getSourceId()
+ java.lang.String getSubtitle()
+ java.lang.String getTemplate()
+ java.lang.String getTitle()
+ java.lang.String getTname()
+ java.lang.String getTopic_background()
+ java.lang.String getTopicid()
+ java.lang.Integer getUpTimes()
+ java.lang.String getUrl()
+ java.lang.String getUrl_3w()
+ java.lang.Integer getVotecount()
+ java.lang.String component1()
+ java.lang.String component2()
+ java.lang.String component3()
+ java.lang.Integer component4()
+ java.lang.String component5()
+ java.lang.String component6()
+ java.lang.String component7()
+ java.lang.Integer component8()
+ java.lang.String component9()
+ java.lang.String component10()
+ java.lang.Integer component11()
+ java.lang.Boolean component12()
+ java.lang.Integer component13()
+ java.lang.Boolean component14()
+ java.lang.Integer component15()
+ java.lang.String component16()
+ java.lang.String component17()
+ java.lang.String component18()
+ java.lang.String component19()
+ java.lang.Integer component20()
+ java.lang.String component21()
+ java.lang.String component22()
+ java.lang.Integer component23()
+ java.lang.String component24()
+ java.lang.Integer component25()
+ java.lang.Integer component26()
+ java.lang.Integer component27()
+ java.lang.String component28()
+ java.lang.String component29()
+ java.lang.String component30()
+ java.lang.String component31()
+ java.lang.String component32()
+ java.lang.String component33()
+ java.lang.String component34()
+ java.lang.String component35()
+ java.lang.Integer component36()
+ java.lang.String component37()
+ java.lang.String component38()
+ java.lang.Integer component39()
+ com.he.fastandroid.entity.NewsList.NewsItem copy(java.lang.String,java.lang.String,java.lang.String,java.lang.Integer,java.lang.String,java.lang.String,java.lang.String,java.lang.Integer,java.lang.String,java.lang.String,java.lang.Integer,java.lang.Boolean,java.lang.Integer,java.lang.Boolean,java.lang.Integer,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.Integer,java.lang.String,java.lang.String,java.lang.Integer,java.lang.String,java.lang.Integer,java.lang.Integer,java.lang.Integer,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.Integer,java.lang.String,java.lang.String,java.lang.Integer)
+ java.lang.String toString()
+ int hashCode()
+ boolean equals(java.lang.Object)
}
class error.NonExistentClass {
}
class com.he.fastandroid.ui.widget.RecyclerViewItemDecoration {
- android.content.Context context
- int orientation
- int dividerHeight
- int dividerColor
- android.graphics.drawable.Drawable mDivider
- android.graphics.Paint mPaint
- int[] attrs
+ void getItemOffsets(android.graphics.Rect,android.view.View,androidx.recyclerview.widget.RecyclerView,androidx.recyclerview.widget.RecyclerView.State)
+ void onDraw(android.graphics.Canvas,androidx.recyclerview.widget.RecyclerView,androidx.recyclerview.widget.RecyclerView.State)
- void drawVertical(android.graphics.Canvas,androidx.recyclerview.widget.RecyclerView)
- void drawHorizontal(android.graphics.Canvas,androidx.recyclerview.widget.RecyclerView)
}
class com.he.fastandroid.ui.fragment.LoginMobileNumberFragment {
- cn.smssdk.EventHandler eventhandler
- android.os.CountDownTimer countDownTimer
- {static} java.lang.String TAG
- {static} java.lang.String DEFAULT_COUNTRY_ID
+ {static} com.he.fastandroid.ui.fragment.LoginMobileNumberFragment.Companion Companion
- java.util.HashMap _$_findViewCache
# int getlayoutId()
# void initView()
# void initData()
- void cheackButtonState()
- void initCountDown()
- void initSMSSDK()
- void processError(java.lang.Object)
+ void onDestroy()
+ {static} com.he.fastandroid.ui.fragment.LoginMobileNumberFragment newInstance()
}
class com.he.fastandroid.ui.fragment.LoginMobileNumberFragment.Companion {
+ com.he.fastandroid.ui.fragment.LoginMobileNumberFragment newInstance()
}
class com.he.fastandroid.ui.fragment.LoginHostFragment {
+ {static} com.he.fastandroid.ui.fragment.LoginHostFragment.Companion Companion
- java.util.HashMap _$_findViewCache
# int getlayoutId()
# void initView()
# void initData()
- void loginUmengClient(com.hjq.umeng.Platform)
+ void onActivityResult(int,int,android.content.Intent)
+ void onSucceed(com.hjq.umeng.Platform,com.hjq.umeng.UmengLogin.LoginData)
+ void onError(com.hjq.umeng.Platform,java.lang.Throwable)
+ void onCancel(com.hjq.umeng.Platform)
+ {static} com.he.fastandroid.ui.fragment.LoginHostFragment newInstance()
}
class com.he.fastandroid.ui.fragment.LoginHostFragment.Companion {
+ com.he.fastandroid.ui.fragment.LoginHostFragment newInstance()
}
class com.he.fastandroid.entity.VideoList {
+ boolean remove(com.he.fastandroid.entity.VideoList.VideoItem)
+ boolean remove(java.lang.Object)
+ boolean contains(com.he.fastandroid.entity.VideoList.VideoItem)
+ boolean contains(java.lang.Object)
+ com.he.fastandroid.entity.VideoList.VideoItem removeAt(int)
+ com.he.fastandroid.entity.VideoList.VideoItem remove(int)
+ int indexOf(com.he.fastandroid.entity.VideoList.VideoItem)
+ int indexOf(java.lang.Object)
+ int lastIndexOf(com.he.fastandroid.entity.VideoList.VideoItem)
+ int lastIndexOf(java.lang.Object)
+ int getSize()
+ int size()
}
class com.he.fastandroid.entity.VideoList.VideoItem {
- java.lang.String cover
- java.lang.String description
- java.lang.Integer length
- java.lang.String m3u8Hd_url
- java.lang.String m3u8_url
- java.lang.String mp4Hd_url
- java.lang.String mp4_url
- java.lang.Integer playCount
- java.lang.Integer playersize
- java.lang.String ptime
- java.lang.String replyBoard
- java.lang.Integer replyCount
- java.lang.String replyid
- java.lang.String sectiontitle
- java.lang.Integer sizeHD
- java.lang.Integer sizeSD
- java.lang.Integer sizeSHD
- java.lang.String title
- java.lang.String topicDesc
- java.lang.String topicImg
- java.lang.String topicName
- java.lang.String topicSid
- java.lang.String vid
- com.he.fastandroid.entity.VideoList.VideoItem.VideoTopic videoTopic
- java.lang.String videosource
- java.lang.Integer votecount
+ java.lang.String getCover()
+ java.lang.String getDescription()
+ java.lang.Integer getLength()
+ java.lang.String getM3u8Hd_url()
+ java.lang.String getM3u8_url()
+ java.lang.String getMp4Hd_url()
+ java.lang.String getMp4_url()
+ java.lang.Integer getPlayCount()
+ java.lang.Integer getPlayersize()
+ java.lang.String getPtime()
+ java.lang.String getReplyBoard()
+ java.lang.Integer getReplyCount()
+ java.lang.String getReplyid()
+ java.lang.String getSectiontitle()
+ java.lang.Integer getSizeHD()
+ java.lang.Integer getSizeSD()
+ java.lang.Integer getSizeSHD()
+ java.lang.String getTitle()
+ java.lang.String getTopicDesc()
+ java.lang.String getTopicImg()
+ java.lang.String getTopicName()
+ java.lang.String getTopicSid()
+ java.lang.String getVid()
+ com.he.fastandroid.entity.VideoList.VideoItem.VideoTopic getVideoTopic()
+ java.lang.String getVideosource()
+ java.lang.Integer getVotecount()
+ java.lang.String component1()
+ java.lang.String component2()
+ java.lang.Integer component3()
+ java.lang.String component4()
+ java.lang.String component5()
+ java.lang.String component6()
+ java.lang.String component7()
+ java.lang.Integer component8()
+ java.lang.Integer component9()
+ java.lang.String component10()
+ java.lang.String component11()
+ java.lang.Integer component12()
+ java.lang.String component13()
+ java.lang.String component14()
+ java.lang.Integer component15()
+ java.lang.Integer component16()
+ java.lang.Integer component17()
+ java.lang.String component18()
+ java.lang.String component19()
+ java.lang.String component20()
+ java.lang.String component21()
+ java.lang.String component22()
+ java.lang.String component23()
+ com.he.fastandroid.entity.VideoList.VideoItem.VideoTopic component24()
+ java.lang.String component25()
+ java.lang.Integer component26()
+ com.he.fastandroid.entity.VideoList.VideoItem copy(java.lang.String,java.lang.String,java.lang.Integer,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.Integer,java.lang.Integer,java.lang.String,java.lang.String,java.lang.Integer,java.lang.String,java.lang.String,java.lang.Integer,java.lang.Integer,java.lang.Integer,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,com.he.fastandroid.entity.VideoList.VideoItem.VideoTopic,java.lang.String,java.lang.Integer)
+ java.lang.String toString()
+ int hashCode()
+ boolean equals(java.lang.Object)
}
class com.he.fastandroid.entity.VideoList.VideoItem.VideoTopic {
- java.lang.String alias
- java.lang.String ename
- java.lang.String tid
- java.lang.String tname
- java.lang.String topic_icons
+ java.lang.String getAlias()
+ java.lang.String getEname()
+ java.lang.String getTid()
+ java.lang.String getTname()
+ java.lang.String getTopic_icons()
+ java.lang.String component1()
+ java.lang.String component2()
+ java.lang.String component3()
+ java.lang.String component4()
+ java.lang.String component5()
+ com.he.fastandroid.entity.VideoList.VideoItem.VideoTopic copy(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)
+ java.lang.String toString()
+ int hashCode()
+ boolean equals(java.lang.Object)
}
class com.he.fastandroid.ui.fragment.LoginHostFragmentDirections {
+ {static} com.he.fastandroid.ui.fragment.LoginHostFragmentDirections.Companion Companion
}
class com.he.fastandroid.ui.fragment.LoginHostFragmentDirections.Companion {
+ androidx.navigation.NavDirections actionLoginHostFragmentToLoginMobileNumberFragment()
+ androidx.navigation.NavDirections actionLoginHostFragmentToLoginPassWordFragment()
}
class com.he.fastandroid.ui.activity.LoginActivity {
- java.util.HashMap _$_findViewCache
# int getlayoutId()
# void initView(android.os.Bundle)
# void initData()
}
class com.he.fastandroid.ui.adapter.VideoAdapter {
+ {static} java.lang.String TAG
+ {static} com.he.fastandroid.ui.adapter.VideoAdapter.Companion Companion
# void convert(com.chad.library.adapter.base.viewholder.BaseViewHolder,com.he.fastandroid.entity.VideoList.VideoItem)
}
class com.he.fastandroid.ui.adapter.VideoAdapter.Companion {
}
interface com.he.fastandroid.room.UserDao {
+ {abstract}java.lang.Object getAll(kotlin.coroutines.Continuation<? super java.util.List<com.he.fastandroid.room.User>>)
+ {abstract}java.lang.Object loadAllByIds(int[],kotlin.coroutines.Continuation<? super java.util.List<com.he.fastandroid.room.User>>)
+ {abstract}java.lang.Object findByName(java.lang.String,kotlin.coroutines.Continuation<? super com.he.fastandroid.room.User>)
+ {abstract}java.lang.Object deleteAllUser(kotlin.coroutines.Continuation<? super kotlin.Unit>)
+ {abstract}java.lang.Object insertAll(com.he.fastandroid.room.User[],kotlin.coroutines.Continuation<? super kotlin.Unit>)
+ {abstract}java.lang.Object update(com.he.fastandroid.room.User,kotlin.coroutines.Continuation<? super kotlin.Unit>)
+ {abstract}java.lang.Object delete(com.he.fastandroid.room.User,kotlin.coroutines.Continuation<? super kotlin.Unit>)
}
interface com.he.fastandroid.remote.ApiService {
+ {abstract}java.lang.Object getRandPwd(java.lang.String,kotlin.coroutines.Continuation<? super retrofit2.Response<com.he.fastandroid.entity.RandPwdResponse>>)
+ {abstract}java.lang.Object getRandPortrait(java.lang.String,java.lang.String,kotlin.coroutines.Continuation<? super com.he.fastandroid.entity.RandPortraitResponse>)
+ {abstract}java.lang.Object getVideo(java.lang.String,java.lang.String,kotlin.coroutines.Continuation<? super com.he.fastandroid.entity.BaseResponse<com.he.fastandroid.entity.VideoList>>)
+ {abstract}java.lang.Object getNews(java.lang.String,java.lang.String,kotlin.coroutines.Continuation<? super com.he.fastandroid.entity.BaseResponse<com.he.fastandroid.entity.NewsList>>)
}
class com.he.fastandroid.remote.ApiService.DefaultImpls {
}
abstract class com.he.fastandroid.room.AppDatabase {
+ {static} java.lang.String DATABASE_NAME
- {static} com.he.fastandroid.room.AppDatabase sInstance
+ {static} com.he.fastandroid.room.AppDatabase.Companion Companion
+ {abstract}com.he.fastandroid.room.UserDao userDao()
}
class com.he.fastandroid.room.AppDatabase.Companion {
+ com.he.fastandroid.room.AppDatabase getInstance(android.content.Context)
}
class com.he.fastandroid.ui.activity.MainActivity {
- java.util.HashMap _$_findViewCache
# int getlayoutId()
# void initView(android.os.Bundle)
# void initData()
# void onRestoreInstanceState(android.os.Bundle)
- void setupBottomNavigationBar()
+ void onBackPressed()
# void onPause()
# void onResume()
# void onDestroy()
}
class com.he.fastandroid.ui.fragment.LoginPassWordFragment {
- {static} java.lang.String TAG
+ {static} com.he.fastandroid.ui.fragment.LoginPassWordFragment.Companion Companion
- java.util.HashMap _$_findViewCache
# int getlayoutId()
# void initView()
# void initData()
- void cheackButtonState()
+ {static} com.he.fastandroid.ui.fragment.LoginPassWordFragment newInstance()
}
class com.he.fastandroid.ui.fragment.LoginPassWordFragment.Companion {
+ com.he.fastandroid.ui.fragment.LoginPassWordFragment newInstance()
}
class com.he.fastandroid.room.User {
- int uid
- java.lang.String userName
- java.lang.String userPassword
- java.lang.String userPortrai
+ int getUid()
+ java.lang.String getUserName()
+ java.lang.String getUserPassword()
+ java.lang.String getUserPortrai()
+ void setUserPortrai(java.lang.String)
+ int component1()
+ java.lang.String component2()
+ java.lang.String component3()
+ java.lang.String component4()
+ com.he.fastandroid.room.User copy(int,java.lang.String,java.lang.String,java.lang.String)
+ java.lang.String toString()
+ int hashCode()
+ boolean equals(java.lang.Object)
}
class com.hjq.umeng.UmengClient {
+ {static} void init(Application)
+ {static} void share(Activity,Platform,UmengShare.ShareData,UmengShare.OnShareListener)
+ {static} void login(Activity,Platform,UmengLogin.OnLoginListener)
+ {static} void onActivityResult(Activity,int,int,Intent)
+ {static} boolean isAppInstalled(Context,Platform)
- {static} boolean isAppInstalled(Context,String)
}
class com.he.fastandroid.room.UserDao_Impl {
- RoomDatabase __db
- EntityInsertionAdapter<User> __insertionAdapterOfUser
- EntityDeletionOrUpdateAdapter<User> __deletionAdapterOfUser
- EntityDeletionOrUpdateAdapter<User> __updateAdapterOfUser
- SharedSQLiteStatement __preparedStmtOfDeleteAllUser
+ Object insertAll(User[],Continuation<? super Unit>)
+ Object delete(User,Continuation<? super Unit>)
+ Object update(User,Continuation<? super Unit>)
+ Object deleteAllUser(Continuation<? super Unit>)
+ Object getAll(Continuation<? super List<User>>)
+ Object loadAllByIds(int[],Continuation<? super List<User>>)
+ Object findByName(String,Continuation<? super User>)
}
class com.he.fastandroid.ui.widget.ClearEditText {
- android.graphics.drawable.Drawable mClearDrawable
- boolean hasFocus
- java.util.HashMap _$_findViewCache
- void init()
+ boolean onTouchEvent(android.view.MotionEvent)
+ void onFocusChange(android.view.View,boolean)
- void setClearIconVisible(boolean)
+ void onTextChanged(java.lang.CharSequence,int,int,int)
+ void beforeTextChanged(java.lang.CharSequence,int,int,int)
+ void afterTextChanged(android.text.Editable)
}
class com.he.fastandroid.BuildConfig {
+ {static} boolean DEBUG
+ {static} String APPLICATION_ID
+ {static} String BUILD_TYPE
+ {static} int VERSION_CODE
+ {static} String VERSION_NAME
}
class com.he.fastandroid.entity.RandPortraitResponse {
- java.lang.String pic_url
+ java.lang.String getPic_url()
+ java.lang.String component1()
+ com.he.fastandroid.entity.RandPortraitResponse<Data> copy(java.lang.String)
+ java.lang.String toString()
+ int hashCode()
+ boolean equals(java.lang.Object)
}
class com.he.fastandroid.ui.activity.SplashActivity {
- com.he.common.utils.PreferenceUtils firstStart$delegate
- java.util.HashMap _$_findViewCache
- boolean getFirstStart()
- void setFirstStart(boolean)
# int getlayoutId()
# void initView(android.os.Bundle)
# void initData()
# void onDestroy()
}
class com.he.fastandroid.entity.BaseResponse {
- java.lang.Integer code
- java.lang.String msg
- Data data
+ java.lang.Integer getCode()
+ java.lang.String getMsg()
+ Data getData()
+ boolean isOk()
}
class com.hjq.umeng.BuildConfig {
+ {static} boolean DEBUG
+ {static} String LIBRARY_PACKAGE_NAME
+ {static} String BUILD_TYPE
+ {static} int VERSION_CODE
+ {static} String VERSION_NAME
}
class com.he.fastandroid.ui.fragment.LoginSignUpFragment {
+ {static} com.he.fastandroid.ui.fragment.LoginSignUpFragment.Companion Companion
- java.util.HashMap _$_findViewCache
# int getlayoutId()
# void initView()
# void initData()
- void cheackButtonState()
+ {static} com.he.fastandroid.ui.fragment.LoginSignUpFragment newInstance()
}
class com.he.fastandroid.ui.fragment.LoginSignUpFragment.Companion {
+ com.he.fastandroid.ui.fragment.LoginSignUpFragment newInstance()
}
class com.he.fastandroid.ui.fragment.NewsFragment {
- com.he.fastandroid.ui.adapter.NewsAdapter newsAdapter
+ {static} com.he.fastandroid.ui.fragment.NewsFragment.Companion Companion
- java.util.HashMap _$_findViewCache
# int getlayoutId()
# void initView()
# void initData()
+ {static} com.he.fastandroid.ui.fragment.NewsFragment newInstance()
}
class com.he.fastandroid.ui.fragment.NewsFragment.Companion {
+ com.he.fastandroid.ui.fragment.NewsFragment newInstance()
}
class com.he.fastandroid.entity.Constant {
+ {static} java.lang.String SP_FIRST_START
+ {static} java.lang.String SP_USER_NAME
+ {static} com.he.fastandroid.entity.Constant INSTANCE
}
class com.he.fastandroid.navigation.NavManager {
- kotlin.jvm.functions.Function1<? super androidx.navigation.NavDirections,kotlin.Unit> navEventListener
+ void navigate(androidx.navigation.NavDirections)
+ void setOnNavEvent(kotlin.jvm.functions.Function1<? super androidx.navigation.NavDirections,kotlin.Unit>)
}
class com.he.fastandroid.remote.Service {
- {static} java.lang.String API_BASE_URL
- {static} java.lang.String API_BASE_URL_v2
- {static} boolean DEBUG
- {static} long CONNECT_TIMEOUT
- {static} long READ_TIMEOUT
- {static} long WRITE_TIMEOUT
- {static} kotlin.Lazy apiService$delegate
- {static} kotlin.Lazy apiServiceV2$delegate
+ {static} com.he.fastandroid.remote.Service INSTANCE
+ com.he.fastandroid.remote.ApiService getApiService()
+ com.he.fastandroid.remote.ApiService getApiServiceV2()
}
class com.he.fastandroid.MyApplication {
- com.he.common.utils.PreferenceUtils spUserName$delegate
- {static} java.lang.String TAG
+ {static} com.he.fastandroid.MyApplication instance
+ {static} com.he.fastandroid.MyApplication.Companion Companion
+ java.lang.String getSpUserName()
+ void setSpUserName(java.lang.String)
# void attachBaseContext(android.content.Context)
+ void onCreate()
}
class com.he.fastandroid.MyApplication.Companion {
+ com.he.fastandroid.MyApplication getInstance()
+ void setInstance(com.he.fastandroid.MyApplication)
}
class com.hjq.umeng.UmengShare {
}
class com.hjq.umeng.UmengShare.ShareData {
- Context mContext
- String mShareTitle
- String mShareUrl
- String mShareDescription
- UMImage mShareLogo
+ void setShareTitle(String)
+ void setShareUrl(String)
+ void setShareDescription(String)
+ void setShareLogo(String)
+ void setShareLogo(int)
+ String getShareUrl()
~ UMWeb create()
}
class com.hjq.umeng.UmengShare.ShareListenerWrapper {
- Platform mPlatform
+ void onStart(SHARE_MEDIA)
+ void onResult(SHARE_MEDIA)
+ void onError(SHARE_MEDIA,Throwable)
+ void onCancel(SHARE_MEDIA)
}
interface com.hjq.umeng.UmengShare.OnShareListener {
~ void onSucceed(Platform)
~ void onError(Platform,Throwable)
~ void onCancel(Platform)
}
class com.hjq.demo.wxapi.WXEntryActivity {
}
class com.he.fastandroid.room.AppDatabase_Impl {
- UserDao _userDao
# SupportSQLiteOpenHelper createOpenHelper(DatabaseConfiguration)
# InvalidationTracker createInvalidationTracker()
+ void clearAllTables()
+ UserDao userDao()
}
class com.hjq.umeng.UmengLogin {
}
class com.hjq.umeng.UmengLogin.LoginData {
- String mId
- String mName
- String mSex
- String mAvatar
- String mToken
+ String getName()
+ String getSex()
+ String getAvatar()
+ String getId()
+ String getToken()
+ boolean isMan()
}
class com.hjq.umeng.UmengLogin.LoginListenerWrapper {
- Platform mPlatform
+ void onStart(SHARE_MEDIA)
+ void onComplete(SHARE_MEDIA,int,Map<String,String>)
+ void onError(SHARE_MEDIA,int,Throwable)
+ void onCancel(SHARE_MEDIA,int)
}
interface com.hjq.umeng.UmengLogin.OnLoginListener {
~ void onSucceed(Platform,LoginData)
~ void onError(Platform,Throwable)
~ void onCancel(Platform)
}
class com.he.fastandroid.ui.fragment.LoginPassWordFragmentDirections {
+ {static} com.he.fastandroid.ui.fragment.LoginPassWordFragmentDirections.Companion Companion
}
class com.he.fastandroid.ui.fragment.LoginPassWordFragmentDirections.Companion {
+ androidx.navigation.NavDirections actionLoginPassWordFragmentToLoginSignUpFragment()
}
class com.he.fastandroid.ui.fragment.UserFragment {
+ {static} com.he.fastandroid.ui.fragment.UserFragment.Companion Companion
- java.util.HashMap _$_findViewCache
# int getlayoutId()
# void initView()
# void initData()
+ {static} com.he.fastandroid.ui.fragment.UserFragment newInstance()
}
class com.he.fastandroid.ui.fragment.UserFragment.Companion {
+ com.he.fastandroid.ui.fragment.UserFragment newInstance()
}
class com.he.fastandroid.entity.RandPwdResponse {
- java.lang.String password
+ java.lang.String getPassword()
+ java.lang.String component1()
+ com.he.fastandroid.entity.RandPwdResponse<Data> copy(java.lang.String)
+ java.lang.String toString()
+ int hashCode()
+ boolean equals(java.lang.Object)
}
class com.he.http.BuildConfig {
+ {static} boolean DEBUG
+ {static} String LIBRARY_PACKAGE_NAME
+ {static} String BUILD_TYPE
+ {static} int VERSION_CODE
+ {static} String VERSION_NAME
}
class com.he.fastandroid.ui.widget.SpaceItemDecoration {
- android.graphics.drawable.Drawable mDivider
- int mSectionOffsetV
- int mSectionOffsetH
- boolean mDrawOver
- int[] attrs
+ void onDrawOver(android.graphics.Canvas,androidx.recyclerview.widget.RecyclerView,androidx.recyclerview.widget.RecyclerView.State)
+ void onDraw(android.graphics.Canvas,androidx.recyclerview.widget.RecyclerView,androidx.recyclerview.widget.RecyclerView.State)
+ void getItemOffsets(android.graphics.Rect,android.view.View,androidx.recyclerview.widget.RecyclerView,androidx.recyclerview.widget.RecyclerView.State)
- void draw(android.graphics.Canvas,androidx.recyclerview.widget.RecyclerView)
- int getOrientation(androidx.recyclerview.widget.RecyclerView.LayoutManager)
}
class com.he.common.BuildConfig {
+ {static} boolean DEBUG
+ {static} String LIBRARY_PACKAGE_NAME
+ {static} String BUILD_TYPE
+ {static} int VERSION_CODE
+ {static} String VERSION_NAME
}
class com.he.fastandroid.ui.activity.BrowserActivity {
+ {static} java.lang.String BROWSER_URL
+ {static} com.he.fastandroid.ui.activity.BrowserActivity.Companion Companion
- java.util.HashMap _$_findViewCache
# int getlayoutId()
# void initView(android.os.Bundle)
# void initData()
}
class com.he.fastandroid.ui.activity.BrowserActivity.Companion {
}
class com.he.fastandroid.ui.fragment.VideoFragment {
- com.he.fastandroid.ui.adapter.VideoAdapter listNormalAdapter
+ {static} com.he.fastandroid.ui.fragment.VideoFragment.Companion Companion
- java.util.HashMap _$_findViewCache
# int getlayoutId()
# void initView()
# void initData()
+ {static} com.he.fastandroid.ui.fragment.VideoFragment newInstance()
}
class com.he.fastandroid.ui.fragment.VideoFragment.Companion {
+ com.he.fastandroid.ui.fragment.VideoFragment newInstance()
}


com.he.fastandroid.ui.adapter.BaseQuickAdapter <|-- com.he.fastandroid.ui.adapter.NewsAdapter
com.he.fastandroid.entity.ArrayList <|-- com.he.fastandroid.entity.NewsList
com.he.fastandroid.entity.NewsList +.. com.he.fastandroid.entity.NewsList.NewsItem
com.he.fastandroid.ui.widget.ItemDecoration <|-- com.he.fastandroid.ui.widget.RecyclerViewItemDecoration
com.he.fastandroid.ui.fragment.BaseFragment <|-- com.he.fastandroid.ui.fragment.LoginMobileNumberFragment
com.he.fastandroid.ui.fragment.LoginMobileNumberFragment +.. com.he.fastandroid.ui.fragment.LoginMobileNumberFragment.Companion
com.he.fastandroid.ui.fragment.OnLoginListener <|.. com.he.fastandroid.ui.fragment.LoginHostFragment
com.he.fastandroid.ui.fragment.BaseFragment <|-- com.he.fastandroid.ui.fragment.LoginHostFragment
com.he.fastandroid.ui.fragment.LoginHostFragment +.. com.he.fastandroid.ui.fragment.LoginHostFragment.Companion
com.he.fastandroid.entity.ArrayList <|-- com.he.fastandroid.entity.VideoList
com.he.fastandroid.entity.VideoList +.. com.he.fastandroid.entity.VideoList.VideoItem
com.he.fastandroid.entity.VideoList.VideoItem +.. com.he.fastandroid.entity.VideoList.VideoItem.VideoTopic
com.he.fastandroid.ui.fragment.LoginHostFragmentDirections +.. com.he.fastandroid.ui.fragment.LoginHostFragmentDirections.Companion
com.he.fastandroid.ui.activity.BaseActivity <|-- com.he.fastandroid.ui.activity.LoginActivity
com.he.fastandroid.ui.adapter.BaseQuickAdapter <|-- com.he.fastandroid.ui.adapter.VideoAdapter
com.he.fastandroid.ui.adapter.VideoAdapter +.. com.he.fastandroid.ui.adapter.VideoAdapter.Companion
com.he.fastandroid.remote.ApiService +.. com.he.fastandroid.remote.ApiService.DefaultImpls
com.he.fastandroid.room.RoomDatabase <|-- com.he.fastandroid.room.AppDatabase
com.he.fastandroid.room.AppDatabase +.. com.he.fastandroid.room.AppDatabase.Companion
com.he.fastandroid.ui.activity.BaseActivity <|-- com.he.fastandroid.ui.activity.MainActivity
com.he.fastandroid.ui.fragment.BaseFragment <|-- com.he.fastandroid.ui.fragment.LoginPassWordFragment
com.he.fastandroid.ui.fragment.LoginPassWordFragment +.. com.he.fastandroid.ui.fragment.LoginPassWordFragment.Companion
com.he.fastandroid.room.UserDao <|.. com.he.fastandroid.room.UserDao_Impl
com.he.fastandroid.ui.widget.OnFocusChangeListener <|.. com.he.fastandroid.ui.widget.ClearEditText
com.he.fastandroid.ui.widget.TextWatcher <|.. com.he.fastandroid.ui.widget.ClearEditText
com.he.fastandroid.ui.widget.AppCompatEditText <|-- com.he.fastandroid.ui.widget.ClearEditText
com.he.fastandroid.entity.BaseResponse <|-- com.he.fastandroid.entity.RandPortraitResponse
com.he.fastandroid.ui.activity.BaseActivity <|-- com.he.fastandroid.ui.activity.SplashActivity
com.he.fastandroid.ui.fragment.BaseFragment <|-- com.he.fastandroid.ui.fragment.LoginSignUpFragment
com.he.fastandroid.ui.fragment.LoginSignUpFragment +.. com.he.fastandroid.ui.fragment.LoginSignUpFragment.Companion
com.he.fastandroid.ui.fragment.BaseFragment <|-- com.he.fastandroid.ui.fragment.NewsFragment
com.he.fastandroid.ui.fragment.NewsFragment +.. com.he.fastandroid.ui.fragment.NewsFragment.Companion
com.he.fastandroid.Application <|-- com.he.fastandroid.MyApplication
com.he.fastandroid.MyApplication +.. com.he.fastandroid.MyApplication.Companion
com.hjq.umeng.UmengShare +.. com.hjq.umeng.UmengShare.ShareData
com.hjq.umeng.UmengShare +.. com.hjq.umeng.UmengShare.ShareListenerWrapper
com.hjq.umeng.UMShareListener <|.. com.hjq.umeng.UmengShare.ShareListenerWrapper
com.hjq.umeng.SoftReference <|-- com.hjq.umeng.UmengShare.ShareListenerWrapper
com.hjq.umeng.UmengShare +.. com.hjq.umeng.UmengShare.OnShareListener
com.umeng.socialize.weixin.view.WXCallbackActivity <|-- com.hjq.demo.wxapi.WXEntryActivity
com.he.fastandroid.room.AppDatabase <|-- com.he.fastandroid.room.AppDatabase_Impl
com.hjq.umeng.UmengLogin +.. com.hjq.umeng.UmengLogin.LoginData
com.hjq.umeng.UmengLogin +.. com.hjq.umeng.UmengLogin.LoginListenerWrapper
com.hjq.umeng.UMAuthListener <|.. com.hjq.umeng.UmengLogin.LoginListenerWrapper
com.hjq.umeng.SoftReference <|-- com.hjq.umeng.UmengLogin.LoginListenerWrapper
com.hjq.umeng.UmengLogin +.. com.hjq.umeng.UmengLogin.OnLoginListener
com.he.fastandroid.ui.fragment.LoginPassWordFragmentDirections +.. com.he.fastandroid.ui.fragment.LoginPassWordFragmentDirections.Companion
com.he.fastandroid.ui.fragment.BaseFragment <|-- com.he.fastandroid.ui.fragment.UserFragment
com.he.fastandroid.ui.fragment.UserFragment +.. com.he.fastandroid.ui.fragment.UserFragment.Companion
com.he.fastandroid.entity.BaseResponse <|-- com.he.fastandroid.entity.RandPwdResponse
com.he.fastandroid.ui.widget.ItemDecoration <|-- com.he.fastandroid.ui.widget.SpaceItemDecoration
com.he.fastandroid.ui.activity.BaseActivity <|-- com.he.fastandroid.ui.activity.BrowserActivity
com.he.fastandroid.ui.activity.BrowserActivity +.. com.he.fastandroid.ui.activity.BrowserActivity.Companion
com.he.fastandroid.ui.fragment.BaseFragment <|-- com.he.fastandroid.ui.fragment.VideoFragment
com.he.fastandroid.ui.fragment.VideoFragment +.. com.he.fastandroid.ui.fragment.VideoFragment.Companion
@enduml