@startuml
'https://plantuml.com/use-case-diagram

actor "用户" as User
rectangle {
  usecase "视频" as UC1
  usecase "全屏播放" as UC1_1
  usecase "新闻资讯" as UC2
  usecase "浏览器页面" as UC2_1
  usecase "个人中心" as UC3
  usecase "登录" as UC4
  usecase "手机号登录" as UC4_1
  usecase "密码登录" as UC4_2
  usecase "注册账号" as UC4_2_1
  usecase "三方登录" as UC4_3
  usecase "服务器" as UC5
}
User --> UC1
User --> UC2
User --> UC3
User --> UC4
User --> UC5

UC1 --> UC1_1
UC2 --> UC2_1
UC4 --> UC4_1
UC4 --> UC4_2
UC4 --> UC4_3
UC4_2 --> UC4_2_1

@enduml
