@startuml
'https://plantuml.com/use-case-diagram

User --> (MainActivity)
(MainActivity)  --> (Bottom Navigation)
(Bottom Navigation)  --> (MNUE:video)
(Bottom Navigation)  --> (MNUE:news)
(Bottom Navigation)  --> (MNUE:user)
(MNUE:video)-->(VideoFragment)#green;text:green : click mnue
(MNUE:news)-->(NewsFragment)#red;text:red : click mnue
(MNUE:user)-->(UserFragment)#blue;text:blue : click mnue
(VideoFragment)-->(requestApi)#green;text:green : click mnue
(NewsFragment)-->(requestApi)#red;text:red : click mnue
(UserFragment)-->(requestApi)#blue;text:blue : click mnue
(requestApi)-->(show video list)#green
(requestApi)-->(show news list)#red
(requestApi)-->(show user info)#blue
(show video list)-->(BUTTON:full video)#green
(show news list)-->(BUTTON:details news)#red
(show user info)-->(BUTTON:logout)#blue
(BUTTON:full video)-->(FullVideoFragment)#green;text:green : click button
(BUTTON:details news)-->(BrowserActivity)#red;text:red : click button
(BUTTON:logout)-->(Server Database)#blue;text:blue : click button

Server ----------> (Server Database)
(requestApi) <----- (Server Database)
(Server Database)-->(Logout Sussess)#blue
(Logout Sussess)-->(SplashActivity)#blue

@enduml