@startuml
'https://plantuml.com/class-diagram

class com.gamepind.ui.view.webview.BrowserView extends android.widget.FrameLayout{
..fields..
    -DWebView mDWebView
    -ProgressBar mProgressBar
    -HintLayout mHintLayout
    -WebViewClient mWebViewClient
    -WebChromeClient mWebChromeClient
    -boolean webErrorFlag
    -{static} String TAG
    -{static} boolean DEBUG
..constructors..
    +BrowserView(@NotNull Context context)
    +BrowserView(@NotNull Context context, @Nullable AttributeSet attrs)
    +BrowserView(@NotNull Context context, @Nullable AttributeSet attrs, int defStyleAttr)
..methods..
    -void handleWebError(final WebView webView, int errorCode, String errorMessage)
    +DWebView getDWebView()
    +void setBrowserClient(@Nullable WebViewClient client)
    +void setBrowserChromeClient(@Nullable WebChromeClient client)
}
note right of com.gamepind.ui.view.webview.BrowserView : This is a combined view,\nProvide progress bar and error view for webView
@enduml