@startuml
'https://plantuml.com/class-diagram

class com.gamepind.soulmate.ui.actvity.WebViewActivity extends com.gamepind.base.mvp.BaseActivity{
..fields..
    -mUrl: String
    -mForceShowTitleBar: String
    -mDWebView: DWebView
    -isBack:String
    -filePathCallback: ValueCallback<Array<Uri>>
    +{static}BUNDLE_KEY_WEBURL:String
    +{static}BUNDLE_KEY_FROM_INBOX_MESSAGE:String
    +{static}QUERY_PARAMER_TITLE:String
    +{static}REQUEST_CODE_WHATSAPP:Int
    +{static}REQUEST_CODE_CONTACTS:Int
    +{static}REQUEST_CODE_FILE_CHOOSER_ANDROID_5:Int
..override..
    +layoutId()
    +initData()
    +start()
    +initView()
    +onBackPressed()
    +onStop()
    +onDestroy()
    +onActivityResult()
    +onRequestPermissionsResult()
    +onPermissionsGranted()
    +onPermissionsDenied()

..methods..
    -readValueFromUrlStrByParamName()
}
note top of com.gamepind.soulmate.ui.actvity.WebViewActivity :1.The local file dsbridge.js is constructed by default \n 2.Gets the scheme of this URI.if equals http/https ,current webview  Loading \n 3.if Received Ssl Error, Proceed with the SSL certificate. \n 4.if url contains "cst.html#" Provide File Chooser \n 5.if url param contains "force_show_titlebar" and is true,WebViewActivity's titlebar visible,Otherwise gone

class com.gamepind.soulmate.ui.actvity.WebViewActivity.PfgJsApi{
..@JavascriptInterface..
    +setIsBack(isBackStr: Any)
    +close(msg: Any)
    +shareToCommon(p: Any)
    +isOpenNotificationWindow(data: Any): String
    +openSystemSetting(data: Any)
    +closeNotificationWindow(p: Any)
    +openNew(url: Any)
    +openNewWebview(url: Any)
    +getAppInfo(): String
    +getNativeAppInfo(user: Any): String
    +startActivityFromJS(p: Any)
    +getAppVersion(data: Any): String
    +getAppVersionCode(data: Any): String
    +getBridgeServiceVersion(data: Any): String
    +getNotchHeight(data: Any): String
    +openExternalBrowser(url: Any)
    +getAppData(data: Any): String
    +jumpRouter(paramJson: Any)
    +jumpContacts(p: Any)
    +shareEachModal(type: Any)
    +shareByType(type: Any)
    +showShareComponent(p: Any)
    +openMessageDetail(data: Any)
}
note top of com.gamepind.soulmate.ui.actvity.WebViewActivity.PfgJsApi : Common Javascript Interface

class com.gamepind.soulmate.ui.actvity.WebViewActivity.Companion{
..methods..
    +open(context: Context, enum: OpenWebEnum)
    +open(context: Context, url: String, pFromInboxMessageFlag: Boolean? = null)
    +getWebIntent(context: Context, enum: OpenWebEnum, deepLink: Uri? = null): Intent
    +getWebIntent(context: Context, url: String?, pFromInboxMessageFlag: Boolean? = null): Intent
}
enum com.gamepind.soulmate.ui.actvity.WebViewActivity.OpenWebEnum{
 +REFER
 +SLOT
 +LOGIN_HELLP
 +MY_VOUCHER
 +MY_QUERIES
 +HELP_SERVICE_FIRST_PAGE
 +CST_ISSUE
 +HELP_SERVICE_MY_BALANCE
 +HELP_SERVICE_MY_BALANCE_RESULT
}

com.gamepind.soulmate.ui.actvity.WebViewActivity  +.. com.gamepind.soulmate.ui.actvity.WebViewActivity.PfgJsApi
com.gamepind.soulmate.ui.actvity.WebViewActivity  +.. com.gamepind.soulmate.ui.actvity.WebViewActivity.Companion
com.gamepind.soulmate.ui.actvity.WebViewActivity  +.. com.gamepind.soulmate.ui.actvity.WebViewActivity.OpenWebEnum

@enduml